[tool.poetry]
name = "plink_pipelines"
version = "0.1.2-alpha"
description = ""
authors = ["Arnor Sigurdsson <arnor-sigurdsson@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">= 3.8,< 3.10"
pandas = "^1.2.4"
scikit-learn = "^1.0.1"
py = "^1.10.0"
luigi = "^3.0.3"
aislib = "^0.1.6-alpha.0"
pyinstaller = "^4.5.1"
bed-reader = "^0.2.24"
deeplake = "^3.0.13"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.23.1"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
ipykernel = "^6.5.0"
Sphinx = "^4.0.2"
coverage = "^6.1.1"
snakeviz = "^2.1.0"
pytest-cov = "^3.0.0"
pynvim = "^0.4.3"
visidata = "^2.4"
pyinstaller = "^4.3"
pre-commit = "^2.13.0"
black = "^21.5b2"

[tool.poetry.scripts]
plink_pipelines = "plink_pipelines.make_dataset:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
