[tool.poetry]
name = "plink_pipelines"
version = "0.1.1-alpha"
description = ""
authors = ["Arnor Sigurdsson <arnor-sigurdsson@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">= 3.8,< 3.10"
pandas = "^1.2.4"
scikit-learn = "^0.24.2"
py = "^1.10.0"
luigi = "^3.0.3"
aislib = "0.1.4a0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
tox = "^3.23.1"
flake8 = "^3.9.2"
jupyter = "^1.0.0"
ipykernel = "^5.5.5"
Sphinx = "^4.0.2"
coverage = "^5.5"
snakeviz = "^2.1.0"
pytest-cov = "^2.12.1"
pynvim = "^0.4.3"
visidata = "^2.4"
pyinstaller = "^4.3"
pycrypto = "^2.6.1"
pre-commit = "^2.13.0"
black = "^21.5b2"

[tool.poetry.scripts]
plink_pipelines = "plink_pipelines.make_dataset:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
